update destroy

diff --git a/.github/workflows/destroy_stack.yaml b/.github/workflows/destroy_stack.yaml
--- a/.github/workflows/destroy_stack.yaml
+++ b/.github/workflows/destroy_stack.yaml
@@ -64,12 +64,15 @@ jobs:
           export PULUMI_STACK_NAME=${{ github.event.inputs.stack_name }}
           echo "PULUMI_STACK_NAME=$PULUMI_STACK_NAME" >> $GITHUB_ENV
           pulumi config set digitalocean:token ${{ secrets.DO_TOKEN }} --secret
-          pulumi refresh --yes
           pulumi stack select $PULUMI_STACK_NAME
+          pulumi refresh --yes
           OUTPUT=$(pulumi stack output k8s_cluster_id || echo "")
           if [ -n "$OUTPUT" ]; then
             echo "K8S_CLUSTER_ID=$OUTPUT" >> $GITHUB_ENV
             echo "✅ Exported K8S_CLUSTER_ID"
+          else
+            echo "❌ Failed to export K8S_CLUSTER_ID"
+            exit 1
           fi
       - name: 💾Save DigitalOcean kubeconfig
         run: |
