dag

diff --git a/.github/workflows/iac.yaml b/.github/workflows/iac.yaml
--- a/.github/workflows/iac.yaml
+++ b/.github/workflows/iac.yaml
@@ -88,7 +88,9 @@ jobs:
           fi
       - name: ✨Spark Setup
         run: |
-          helm repo add spark-operator https://googlecloudplatform.github.io/spark-on-k8s-operator
+          helm repo add spark-operator https://googlecloudplatform.github.io/spark-on-k8s-operator || echo "mite error out, but its adds it anyway"
+          helm repo list
+          helm repo list | grep spark-operator          
           helm repo update
           helm install spark-operator spark-operator/spark-operator  --set webhook.enable=true --set webhook.port=443 --namespace spark-operator --create-namespace
       - name: 🌀༄ Airflow secret 🔐
