dag

diff --git a/.github/workflows/iac.yaml b/.github/workflows/iac.yaml
--- a/.github/workflows/iac.yaml
+++ b/.github/workflows/iac.yaml
@@ -93,13 +93,17 @@ jobs:
           helm repo add apache-airflow https://airflow.apache.org
           helm repo update
           #helm repo add spark-operator https://googlecloudplatform.github.io/spark-on-k8s-operator # gives 404, was working.
+          helm uninstall spark-operator -n spark-operator  || echo "it ok to fail"
+          helm repo add --force-update spark-operator https://kubeflow.github.io/spark-operator
+          helm repo update
           helm repo list
       - name: ✨Spark Setup
         run: |
-          git clone https://github.com/GoogleCloudPlatform/spark-on-k8s-operator.git
-          cd spark-on-k8s-operator/charts/spark-operator-chart
+          #git clone https://github.com/GoogleCloudPlatform/spark-on-k8s-operator.git
+          #cd spark-on-k8s-operator/charts/spark-operator-chart
           #helm install spark-operator spark-operator/spark-operator  --set webhook.enable=true --set webhook.port=443 --namespace spark-operator --create-namespace
-          helm install spark-operator .  --set webhook.enable=true --set webhook.port=443 --namespace spark-operator --create-namespace
+          #helm install spark-operator .  --set webhook.enable=true --set webhook.port=443 --namespace spark-operator --create-namespace
+          helm install spark-operator spark-operator/spark-operator  --set webhook.enable=true --set webhook.port=443 --namespace spark-operator --create-namespace
           helm repo list
       - name: 🌀༄ Airflow secret 🔐
         run: |
@@ -143,9 +147,15 @@ jobs:
           kubectl apply -n airflow -f airflow-read-configmap-role.yaml
           kubectl apply -n airflow -f spark-rbac-config.yaml
           kubectl apply -n airflow -f spark-rbac.yaml
-      - name: 🚀 airflow dag
+      - name: 🚀 trigger airflow dag
         run: |
-          sleep 600
+          kubectl -n airflow get svc |grep airflow-webserver
+          kubectl -n airflow expose svc airflow-webserver --type=LoadBalancer --name=airflow-lb
+          sleep 180
+          kubectl -n airflow get svc airflow-lb |grep -v NAME |awk '{print $4}' | grep -Eo '([0-9]{1,3}\.){3}[0-9]{1,3}' > airflow-lb-ip.txt
+          export AIRFLOW_LB_IP=$(cat airflow-lb-ip.txt)
+          echo "AIRFLOW_LB_IP=$AIRFLOW_LB_IP" >> $GITHUB_ENV
+
       - name: 🔥Tear down
         if: always()
         run: |
