pipeline setup and run in workflow stages .run12

diff --git a/.github/workflows/setup_run_pipeline.yaml b/.github/workflows/setup_run_pipeline.yaml
--- a/.github/workflows/setup_run_pipeline.yaml
+++ b/.github/workflows/setup_run_pipeline.yaml
@@ -1,9 +1,9 @@
 name: Testing Chicago Car Crash Pipeline
 
 on:
-#  push:
-#    branches:
-#      - dev
+  push:
+    branches:
+      - dev
   workflow_dispatch:
 
 env:
@@ -100,9 +100,9 @@ jobs:
           else
             echo "✅ All nodes are Ready."  
           fi
-  setup_helm_repos:
+  setup_spark_operator:
     runs-on: ubuntu-latest
-    needs: [setup_infra]
+    needs: [ setup_infra ]
     environment: cicd
     steps:
       - name: Checkout repo
@@ -161,56 +161,6 @@ jobs:
           helm repo add --force-update spark-operator https://kubeflow.github.io/spark-operator
           helm repo update
           helm repo list
-
-  setup_spark_operator:
-    runs-on: ubuntu-latest
-    needs: [ setup_infra, setup_helm_repos ]
-    environment: cicd
-    steps:
-      - name: Checkout repo
-        uses: actions/checkout@v3
-
-      - name: Set up Helm
-        uses: azure/setup-helm@v3
-        with:
-          version: v3.14.0
-
-      - name: 🦭Install kubeseal
-        uses: digitalservicebund/setup-kubeseal@v1.0.0
-
-      - name: Install envsubst
-        run: sudo apt-get update && sudo apt-get install -y gettext
-
-      - name: Install doctl
-        uses: digitalocean/action-doctl@v2
-        with:
-          token: ${{ secrets.DO_TOKEN }}
-
-      - name: 🐍Set up Python
-        uses: actions/setup-python@v4
-        with:
-          python-version: '3.11'
-
-      - name: Install dependencies
-        run: |
-          cd infra-as-code
-          python -m pip install --upgrade pip
-          pip install -r requirements.txt
-
-      - name: Install Pulumi CLI
-        uses: pulumi/actions@v4
-        with:
-          pulumi-version: latest
-
-      - name: Login to Pulumi
-        run: pulumi login
-        env:
-          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
-
-      - name: 💾Save DigitalOcean kubeconfig
-        run: |
-          cd infra-as-code
-          doctl kubernetes cluster kubeconfig save ${{ needs.setup_infra.outputs.k8s_cluster_id }}
       - name: ✨Spark Setup
         run: |
           kubectl create namespace airflow || echo "airflow namespace exists"
@@ -282,6 +232,18 @@ jobs:
         run: |
           cd infra-as-code
           doctl kubernetes cluster kubeconfig save ${{ needs.setup_infra.outputs.k8s_cluster_id }}
+      - name: Add helm repos
+        run: |
+          helm repo add sealed-secrets https://bitnami-labs.github.io/sealed-secrets
+          helm repo update
+          helm repo add apache-airflow https://airflow.apache.org
+          helm repo update
+          #helm repo add spark-operator https://googlecloudplatform.github.io/spark-on-k8s-operator # gives 404, was working.
+          helm uninstall spark-operator -n spark-operator  || echo "it ok to fail"
+          helm uninstall airflow -n airflow  || echo "it ok to fail"
+          helm repo add --force-update spark-operator https://kubeflow.github.io/spark-operator
+          helm repo update
+          helm repo list
       - name: 🌀༄ Airflow secret 🔐
         run: |
           kubectl create namespace sealed-secrets  || echo "sealed-secrets namespace exists"
